pipeline:
  build:
    image: arukomp/php71-laravel:latest
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
    commands:
      - composer install --quiet
      - npm install --quiet
      - npm run prod

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=secret

cache:
  mount:
    - node_modules
    - vendor