pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
      - ./vendor
    volumes:
      - /tmp/cache:/cache

  build:
    image: arukomp/php71-laravel:latest
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
    commands:
      - composer install --quiet
      - npm install --quiet
      - npm run prod

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
      - ./vendor
    volumes:
      - /tmp/cache:/cache

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=secret
