pipeline:
  build:
    image: arukomp/php71-laravel:latest
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
    commands:
      - composer install
      - npm install
      - npm run prod

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=secret
