version: 2
jobs:
  build_and_test:
    docker:
      - image: arukomp/php71-laravel:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-dependencies-{{ checksum "composer.json" }}
            # fallback
            - composer-v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: composer-v1-dependencies-{{ checksum "composer.json" }}
      - restore_cache:
          keys:
            - node-v1-dependencies-{{ checksum "package.json" }}
            # fallback
            - node-v1-dependencies-
      - run: npm install --quiet
      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-dependencies-{{ checksum "package.json" }}
      - run: cp .env.testing .env
      - run: php artisan key:generate
      - run: ./vendor/bin/phpunit
      - run: npm run production

  deploy:
    docker:
      - image: arukomp/php71-laravel:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "Deploying to live"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test