version: 2
jobs:
  build_and_test:
    docker:
      - image: arukomp/php71-laravel:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-dependencies-{{ checksum "composer.json" }}
            # fallback
            - composer-v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: composer-v1-dependencies-{{ checksum "composer.json" }}
      - restore_cache:
          keys:
            - node-v1-dependencies-{{ checksum "package.json" }}
            # fallback
            - node-v1-dependencies-
      - run: npm install --quiet
      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-dependencies-{{ checksum "package.json" }}
      - run: php artisan key:generate --env=testing
      - run: ./vendor/bin/phpunit
      - run: npm run production

  deploy:
    docker:
      - image: arukomp/php71-laravel:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setting up SSH
          command: |
            'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
            eval $(ssh-agent -s)
            mkdir -p ~/.ssh
            '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
      - run:
          name: Running Envoy deployment script
          command: envoy run deploy --commit=$CIRCLE_SHA1

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - approve_deployment:
          type: approval
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - approve_deployment
          filters:
            branches:
              only:
                - master